### PR TITLE
Share functions

### PR DESCRIPTION
**Pull request by omatt**
From previous [pull request](https://github.com/franzks/GridofBits/pull/5). Added missing `ShareManager` class.

### CODE REVIEW

**Comment by franzks-zz** [comment]
So I've merged this and all seems to be working (we may remove email though, I'm sure no one will ever use that, hahaha). The problem is when sharing through Facebook's ShareLinkContent, when the link points to a Google Play app, the title and description are actually overridden, so we can't display the user's score (which makes it useless). See this: http://stackoverflow.com/questions/24262169/facebook-sharing-a-play-store-link-using-the-share-dialog

We might decide to use AppLinks as the SO post suggests instead. In the meantime I'm seeing if there are any ways to disable the link title and content being replaced.

**Comment by omatt** [comment]
I just tested it, and ShareDialog cannot override Play Store's url preview. I also tried using `goo.gl` url shortener, but it has no effect. Maybe we really need to use `AppLinks` as you suggested.

**Comment by franzks-zz** [comment]
What do you think of this: http://stackoverflow.com/questions/8269049/posting-a-high-score-in-facebook-from-android-app ?

The code is much more compact, doesn't require additional dependencies, and works on more than just Facebook or Twitter.

**Comment by omatt** [comment]
The issue there is if we use `Intent.ACTION_SEND` - it will show a dialog of all the apps that we can "SEND" something. I remember that I tried filtering the package name of the Facebook app before; similar to what I did to Twitter, but it didn't work.

I call using `Intent.ACTION_SEND` to be lazy, but it works :smile:

**Comment by omatt** [comment]
I'll try using [package name filtering](http://stackoverflow.com/questions/9730243/how-to-filter-specific-apps-for-action-send-intent-and-set-a-different-text-for) again tomorrow.

**Comment by omatt** [comment]
Issue about using [`Intent`](https://developers.facebook.com/bugs/332619626816423) for share via Facebook.

**Comment by omatt** [comment]
[App Links](https://developers.facebook.com/quickstarts/?platform=app-links-host) works great! I tried it :)

**Pull request merged**
