### PR TITLE
Added share functions.

### PR DESCRIPTION
**Pull request by omatt**
I created a `ShareManager` class containing functions for sharing your score/achievements through Facebook, Twitter, and Email(:P).

You don't need to set-up anything for Twitter and Email since I only used Intents. For Facebook, I used their [Android API](https://developers.facebook.com/docs/sharing/android) that requires an `app_id` from the [Developers Console](https://developers.facebook.com/) and you need to supply the console a keyhash. I've already declared the necessary permission `android.permission.INTERNET` in the manifest file.

The "share" looks good to be done in `GameResultActivity`.

### CODE REVIEW

**Comment by franzks-zz** [comment]
Hello Omar, thank you very much for this! I'm currently working on finishing the Google Play Games integration started by #4 , so I'll merge this once I'm finished with that one. Since this is just my weekend for-fun project it might take some time, but I'll get to this soon because I like this feature a lot and was planning to do it in the future anyway, but you saved me some work :)

**Comment by omatt** [comment]
No problem! The functions are not yet invoked and I didn't do any of the UI stuff for the share function yet so that when you merge this feature - the project will still be fine :)

**Comment by franzks-zz** [comment]
Hi Omar, you're describing a new 'ShareManager' class, but from this PR I can't see any reference to it? Also, you're saying that it includes Twitter and Email but I can't see it in the code as well. It might have not been added when you commit?

**Comment by omatt** [comment]
Oh. My bad. Maybe it's not been included when I staged a commit since it's a new class. I'll just make another pull request later or maybe tomorrow :)

**Pull request closed without merging**
